-- マイグレーションの雛形。ファイル名は`NNNN_内容.sql`（4桁の連番＋内容、昇順に適用される）。
--
-- **冪等に書く。** 同じファイルが2回適用されても失敗しない形にする——fresh bootstrap
-- （`create_tables()`がモデルから表と制約を作った直後に全migrationを適用する経路、
-- `scripts/bootstrap_fresh_db.py`・`bootstrap_ci_db.py`）では、モデルが既に作った
-- ものへ同じDDLが走る。`tests/test_migrate.py`がこの経路を検証する。
--
--     ALTER TABLE t ADD COLUMN IF NOT EXISTS c type;
--     CREATE INDEX IF NOT EXISTS idx_x ON t USING btree (c);
--     DROP INDEX IF EXISTS idx_old;
--     -- 制約には ADD CONSTRAINT IF NOT EXISTS が無いため、落としてから付ける
--     ALTER TABLE t DROP CONSTRAINT IF EXISTS t_c_fkey;
--     ALTER TABLE t ADD CONSTRAINT t_c_fkey FOREIGN KEY (c) REFERENCES p (id) ON DELETE CASCADE;
--
-- **`DO $$ ... $$`を使わない。** 適用側（`app/infrastructure/migrate.py:
-- _split_statements`）が`;`で文を分割するため、ブロックの途中で切れて構文エラーになる。
--
-- **`axis_definitions`/`axis_registry_meta`の行データ（INSERT/UPDATE/DELETE）を書かない。**
-- 軸の追加・削除・調整は`axis_admin`のAPI経由が唯一の経路（CLAUDE.md参照）。
-- ここで管理するのはテーブル構造（DDL）だけ。
--
-- 冒頭に、何のための制約・列なのかを現在形で書く（経緯はdocs/records/tasks/Txxx.mdへ）。
